ROTK_ROMANS = [
    "1_ Book V - Chapter 01 - Minas Tirith.mp3",
    "1_ Book V - Chapter 02 - The Passing of the Grey Company.mp3",
    "1_ Book V - Chapter 03 - The Muster of Rohan.mp3",
    "1_ Book V - Chapter 04 - The Siege of Gondor.mp3",
    "1_ Book V - Chapter 05 - The Ride of the Rohirrim.mp3",
    "1_ Book V - Chapter 06 - The Battle of Pelennor Fields.mp3",
    "1_ Book V - Chapter 07 - The Pyre of Denethor.mp3",
    "1_ Book V - Chapter 08 - The Houses of Healing.mp3",
    "1_ Book V - Chapter 09 - The Last Debate.mp3",
    "1_ Book V - Chapter 10 - The Black Gate Opens.mp3",
    "2_ Book VI - Chapter 01 - The Tower of Cirith Ungol.mp3",
    "2_ Book VI - Chapter 02 - The Land of Shadow.mp3",
    "2_ Book VI - Chapter 03 - Mount Doom.mp3",
    "2_ Book VI - Chapter 04 - The Field of Cormallen.mp3",
    "2_ Book VI - Chapter 05 - The Steward & The King.mp3",
    "2_ Book VI - Chapter 06 - Many Partings.mp3",
    "2_ Book VI - Chapter 07 - Homeward Bound.mp3",
    "2_ Book VI - Chapter 08 - The Scouring of the Shire.mp3",
    "2_ Book VI - Chapter 09 - The Grey Havens.mp3",
    "3_ Appendix A - Annals of the Kings and Rulers.mp3",
    "3_ Appendix B - The House of Eorl.mp3",
    "3_ Appendix C - Durin's Folk.mp3",
]

ROTK_NO_ROMANS = [
    "1_ Book  - Chapter 01 - Minas Tirith.mp3",
    "1_ Book  - Chapter 02 - The Passing of the Grey Company.mp3",
    "1_ Book  - Chapter 03 - The Muster of Rohan.mp3",
    "1_ Book  - Chapter 04 - The Siege of Gondor.mp3",
    "1_ Book  - Chapter 05 - The Ride of the Rohirrim.mp3",
    "1_ Book  - Chapter 06 - The Battle of Pelennor Fields.mp3",
    "1_ Book  - Chapter 07 - The Pyre of Denethor.mp3",
    "1_ Book  - Chapter 08 - The Houses of Healing.mp3",
    "1_ Book  - Chapter 09 - The Last Debate.mp3",
    "1_ Book  - Chapter 10 - The Black Gate Opens.mp3",
    "2_ Book  - Chapter 01 - The Tower of Cirith Ungol.mp3",
    "2_ Book  - Chapter 02 - The Land of Shadow.mp3",
    "2_ Book  - Chapter 03 - Mount Doom.mp3",
    "2_ Book  - Chapter 04 - The Field of Cormallen.mp3",
    "2_ Book  - Chapter 05 - The Steward & The King.mp3",
    "2_ Book  - Chapter 06 - Many Partings.mp3",
    "2_ Book  - Chapter 07 - Homeward Bound.mp3",
    "2_ Book  - Chapter 08 - The Scouring of the Shire.mp3",
    "2_ Book  - Chapter 09 - The Grey Havens.mp3",
    "3_ Appendix A - Annals of the Kings and Rulers.mp3",
    "3_ Appendix B - The House of Eorl.mp3",
    "3_ Appendix C - Durin's Folk.mp3",
]

PART_ROMANS = [
    "Part I - Prologue.mp3",
    "Part II - A Long-expected Party.mp3",
    "Part III - Shadow of the Past.mp3",
    "Part IV - Riddles in the Dark.mp3",
    "Part V - The Army of Storms.mp3",
    "Part VI - Epilogue.mp3",
]

PART_NO_ROMANS = [
    "Part  - Prologue.mp3",
    "Part  - A Long-expected Party.mp3",
    "Part  - Shadow of the Past.mp3",
    "Part  - Riddles in the Dark.mp3",
    "Part  - The Army of Storms.mp3",
    "Part  - Epilogue.mp3",
]
